version: "3"
services:
  catalog:
    build: catalog
    ports:
      - 8000:8000
    volumes:
      - ./catalog:/src
  foreign-exchange:
    build: foreign-exchange
    ports:
      - 8001:8001
    volumes:
      - ./foreign-exchange:/src