version: "3"
services:
  nats:
    image: nats:2-scratch
    ports:
      - 4222:4222
      - 8222:8222
  catalog:
    build: catalog
    ports:
      - 8000:8000
    volumes:
      - ./catalog:/src
  foreign-exchange:
    build: foreign-exchange
    ports:
      - 8001:8001
    volumes:
      - ./foreign-exchange:/src